### ISSUE TITLE
Error: Cannot read properties of undefined...

### ISSUE THREAD

**Issue by DryHumorInDC** [PacoVK/antora-confluence#34]
Hello!

I've installed version 0.3.0, however I'm still getting the same error:

```
info: Processing README.html
Cannot read properties of undefined (reading 'pageTitle')
Cause: TypeError
    at ....nvm/v16.20.2/lib/node_modules/antora-confluence/dist/lib/transformer/LinkTransformer.js:98:140

```
Thanks,
Matt

**Comment by PacoVK** [comment]
Hey @DryHumorInDC thanks for reporting this issue. Can you provide a simple example of the source `README.adoc` that causes the issue? Thanks :)

**Comment by DryHumorInDC** [comment]
Thank you for getting back with me.  Actually, I think it's working as designed.   Some of my asciidoc attributes were undefined, so I just had to fix them.  Thanks Again!
