### ISSUE TITLE
Highlighted text is completely removed from Confluence output

### ISSUE THREAD

**Issue by slonopotamus** [PacoVK/antora-confluence#46]
In Asciidoctor, you can use `#text#` to [highlight text](https://docs.asciidoctor.org/asciidoc/latest/text/highlight/), it is a [recommented way to add TODOs](https://github.com/asciidoctor/asciidoctor/issues/2695#issuecomment-383278019). However, highlighted text is completely missing when page is published to Confluence.

UPD: If I comment out [this line](https://github.com/PacoVK/antora-confluence/blob/0.3.2/lib/service/HtmlToConfluenceConverter.ts#L30), highlighted text starts appearing in output game (without any styling, obviously). So, there is something wrong with `rewriteMarks` function, though I didn't understand what exactly yet.

**Comment by slonopotamus** [comment]
See https://github.com/PacoVK/antora-confluence/pull/47 for a proposed fix (+ test).

**Comment by slonopotamus** [comment]
@PacoVK could you please a make new release with this fix?

**Comment by PacoVK** [comment]
@slonopotamus thanks for reaching out again, i was waiting to complete something, but it takes too much time. Just released 0.3.3, thanks for your contribution!
